### ISSUE TITLE
Missing firewall rule add --cidr

### ISSUE THREAD

**Issue by nhanledev** [bizflycloud/bizflyctl#51]
I am trying to create firewall rule via the cli, but it is impossible because it requires CIDR but the `--cidr` flag does not exist

To reproduce, run `.\bizfly.exe firewall rule create <firewallID> --direction ingress --protocol tcp --cidr 127.0.0.1`

![image](https://user-images.githubusercontent.com/28459250/188534217-9dd17e90-7f65-4219-b4eb-bbf1aaa1004e.png)

**Comment by ghost** [comment]
@tung491  please fix this bug.
