### ISSUE TITLE
cloudwatch does not work

### ISSUE THREAD

**Issue by nhanledev** [bizflycloud/bizflyctl#60]
Hello,

I am trying to use cloudwatch in bizflycli to manage my alarm list, but it returns 401 error when being accessed.

I still can do `server list` so it might be a bug on bizflycli end.

![image](https://user-images.githubusercontent.com/28459250/203722767-0c7fa762-ac8e-4563-90ff-d3f98ae5e481.png)

Affected version: 0.2.7, 0.2.8

**Comment by ghost** [comment]
Thanks for your report. We are investigating the issue.

**Comment by ghost** [comment]
THe issue was fixed.
